"""add_requested_role_to_registration_requests

Revision ID: afe18e5a2aa4
Revises: 013
Create Date: 2026-01-29 10:48:28.045775

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe18e5a2aa4'
down_revision: Union[str, None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('object_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreman_id', sa.Integer(), nullable=False),
    sa.Column('cost_object_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_object_id'], ['cost_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foreman_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_access_requests_id'), 'object_access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_object_access_requests_status'), 'object_access_requests', ['status'], unique=False)
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_codes_code'), 'telegram_link_codes', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_link_codes_id'), 'telegram_link_codes', ['id'], unique=False)
    op.create_table('upd_distribution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_cost_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_distribution', sa.JSON(), nullable=True),
    sa.Column('new_distribution', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_cost_id'], ['material_costs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upd_distribution_history_id'), 'upd_distribution_history', ['id'], unique=False)
    op.create_index(op.f('ix_upd_distribution_history_material_cost_id'), 'upd_distribution_history', ['material_cost_id'], unique=False)
    op.create_table('time_sheet_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_sheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['time_sheet_id'], ['time_sheets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_sheet_comments_id'), 'time_sheet_comments', ['id'], unique=False)
    op.create_index(op.f('ix_time_sheet_comments_time_sheet_id'), 'time_sheet_comments', ['time_sheet_id'], unique=False)
    op.add_column('brigade_members', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('brigade_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brigade_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_brigade_members_id'), 'brigade_members', ['id'], unique=False)
    op.drop_column('brigade_members', 'is_active')
    op.drop_column('brigade_members', 'hourly_rate')
    op.alter_column('brigades', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brigades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_brigades_id'), 'brigades', ['id'], unique=False)
    op.alter_column('cost_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('cost_objects', sa.Column('budget_amount', sa.Float(), nullable=True))
    op.add_column('cost_objects', sa.Column('budget_alert_80_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cost_objects', sa.Column('budget_alert_100_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('cost_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('cost_objects_code_key', 'cost_objects', type_='unique')
    op.alter_column('deliveries', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('idx_deliveries_created_by', table_name='deliveries')
    op.drop_index('idx_deliveries_date', table_name='deliveries')
    op.drop_index('idx_deliveries_object', table_name='deliveries')
    op.drop_index('idx_deliveries_status', table_name='deliveries')
    op.create_index(op.f('ix_deliveries_cost_object_id'), 'deliveries', ['cost_object_id'], unique=False)
    op.create_index(op.f('ix_deliveries_created_by_id'), 'deliveries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_deliveries_delivery_date'), 'deliveries', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.drop_constraint('deliveries_created_by_id_fkey', 'deliveries', type_='foreignkey')
    op.drop_constraint('deliveries_cost_object_id_fkey', 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deliveries', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.alter_column('delivery_costs', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('delivery_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_costs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('idx_delivery_costs_created_by', table_name='delivery_costs')
    op.drop_index('idx_delivery_costs_date', table_name='delivery_costs')
    op.drop_index('idx_delivery_costs_object', table_name='delivery_costs')
    op.drop_index('idx_delivery_costs_type', table_name='delivery_costs')
    op.create_index(op.f('ix_delivery_costs_cost_object_id'), 'delivery_costs', ['cost_object_id'], unique=False)
    op.create_index(op.f('ix_delivery_costs_cost_type'), 'delivery_costs', ['cost_type'], unique=False)
    op.create_index(op.f('ix_delivery_costs_created_by_id'), 'delivery_costs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_delivery_costs_date'), 'delivery_costs', ['date'], unique=False)
    op.create_index(op.f('ix_delivery_costs_id'), 'delivery_costs', ['id'], unique=False)
    op.drop_constraint('delivery_costs_created_by_id_fkey', 'delivery_costs', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_costs', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('equipment_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_costs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_orders', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Причина отказа в заявке',
               existing_nullable=True)
    op.alter_column('equipment_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_costs', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('labor_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_costs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('idx_labor_costs_created_by', table_name='labor_costs')
    op.drop_index('idx_labor_costs_date', table_name='labor_costs')
    op.drop_index('idx_labor_costs_object', table_name='labor_costs')
    op.create_index(op.f('ix_labor_costs_cost_object_id'), 'labor_costs', ['cost_object_id'], unique=False)
    op.create_index(op.f('ix_labor_costs_created_by_id'), 'labor_costs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_labor_costs_date'), 'labor_costs', ['date'], unique=False)
    op.create_index(op.f('ix_labor_costs_id'), 'labor_costs', ['id'], unique=False)
    op.drop_constraint('labor_costs_created_by_id_fkey', 'labor_costs', type_='foreignkey')
    op.create_foreign_key(None, 'labor_costs', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('material_costs', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('material_costs', sa.Column('duplicate_checked_at', sa.DateTime(), nullable=True))
    op.alter_column('material_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_costs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'material_costs', 'material_costs', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    op.alter_column('material_requests', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Комментарии к заявке',
               existing_nullable=True)
    op.alter_column('material_requests', 'expected_delivery_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ожидаемая дата доставки',
               existing_nullable=True)
    op.alter_column('material_requests', 'supplier',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Поставщик',
               existing_nullable=True)
    op.alter_column('material_requests', 'order_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Номер заказа у поставщика',
               existing_nullable=True)
    op.alter_column('material_requests', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Причина отклонения заявки',
               existing_nullable=True)
    op.alter_column('material_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('other_costs', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('other_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('other_costs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('idx_other_costs_created_by', table_name='other_costs')
    op.drop_index('idx_other_costs_date', table_name='other_costs')
    op.drop_index('idx_other_costs_object', table_name='other_costs')
    op.create_index(op.f('ix_other_costs_cost_object_id'), 'other_costs', ['cost_object_id'], unique=False)
    op.create_index(op.f('ix_other_costs_created_by_id'), 'other_costs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_other_costs_date'), 'other_costs', ['date'], unique=False)
    op.create_index(op.f('ix_other_costs_id'), 'other_costs', ['id'], unique=False)
    op.drop_constraint('other_costs_created_by_id_fkey', 'other_costs', type_='foreignkey')
    op.create_foreign_key(None, 'other_costs', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('registration_requests', sa.Column('requested_role', sa.String(length=50), nullable=True))
    op.drop_index('ix_telegram_notifications_created_at', table_name='telegram_notifications')
    op.drop_index('ix_telegram_notifications_user_unread', table_name='telegram_notifications')
    op.create_index(op.f('ix_telegram_notifications_id'), 'telegram_notifications', ['id'], unique=False)
    op.drop_constraint('telegram_notifications_user_id_fkey', 'telegram_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_notifications', 'users', ['user_id'], ['id'])
    op.add_column('time_sheets', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.alter_column('time_sheets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('time_sheets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('upd_distribution', sa.Column('material_cost_item_id', sa.Integer(), nullable=True))
    op.add_column('upd_distribution', sa.Column('cost_object_id', sa.Integer(), nullable=True))
    op.alter_column('upd_distribution', 'material_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('upd_distribution', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upd_distribution', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'upd_distribution', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'upd_distribution', 'material_cost_items', ['material_cost_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='telegram_chat_id::integer')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_constraint('users_telegram_chat_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_telegram_chat_id_key', 'users', ['telegram_chat_id'])
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'upd_distribution', type_='foreignkey')
    op.drop_constraint(None, 'upd_distribution', type_='foreignkey')
    op.alter_column('upd_distribution', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upd_distribution', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upd_distribution', 'material_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('upd_distribution', 'cost_object_id')
    op.drop_column('upd_distribution', 'material_cost_item_id')
    op.alter_column('time_sheets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('time_sheets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('time_sheets', 'cancellation_reason')
    op.drop_constraint(None, 'telegram_notifications', type_='foreignkey')
    op.create_foreign_key('telegram_notifications_user_id_fkey', 'telegram_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_telegram_notifications_id'), table_name='telegram_notifications')
    op.create_index('ix_telegram_notifications_user_unread', 'telegram_notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_telegram_notifications_created_at', 'telegram_notifications', ['created_at'], unique=False)
    op.drop_column('registration_requests', 'requested_role')
    op.drop_constraint(None, 'other_costs', type_='foreignkey')
    op.create_foreign_key('other_costs_created_by_id_fkey', 'other_costs', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_other_costs_id'), table_name='other_costs')
    op.drop_index(op.f('ix_other_costs_date'), table_name='other_costs')
    op.drop_index(op.f('ix_other_costs_created_by_id'), table_name='other_costs')
    op.drop_index(op.f('ix_other_costs_cost_object_id'), table_name='other_costs')
    op.create_index('idx_other_costs_object', 'other_costs', ['cost_object_id'], unique=False)
    op.create_index('idx_other_costs_date', 'other_costs', ['date'], unique=False)
    op.create_index('idx_other_costs_created_by', 'other_costs', ['created_by_id'], unique=False)
    op.alter_column('other_costs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('other_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('other_costs', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('material_requests', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_requests', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отклонения заявки',
               existing_nullable=True)
    op.alter_column('material_requests', 'order_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Номер заказа у поставщика',
               existing_nullable=True)
    op.alter_column('material_requests', 'supplier',
               existing_type=sa.VARCHAR(length=255),
               comment='Поставщик',
               existing_nullable=True)
    op.alter_column('material_requests', 'expected_delivery_date',
               existing_type=sa.DATE(),
               comment='Ожидаемая дата доставки',
               existing_nullable=True)
    op.alter_column('material_requests', 'comment',
               existing_type=sa.TEXT(),
               comment='Комментарии к заявке',
               existing_nullable=True)
    op.drop_constraint(None, 'material_costs', type_='foreignkey')
    op.alter_column('material_costs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('material_costs', 'duplicate_checked_at')
    op.drop_column('material_costs', 'duplicate_of_id')
    op.drop_constraint(None, 'labor_costs', type_='foreignkey')
    op.create_foreign_key('labor_costs_created_by_id_fkey', 'labor_costs', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_labor_costs_id'), table_name='labor_costs')
    op.drop_index(op.f('ix_labor_costs_date'), table_name='labor_costs')
    op.drop_index(op.f('ix_labor_costs_created_by_id'), table_name='labor_costs')
    op.drop_index(op.f('ix_labor_costs_cost_object_id'), table_name='labor_costs')
    op.create_index('idx_labor_costs_object', 'labor_costs', ['cost_object_id'], unique=False)
    op.create_index('idx_labor_costs_date', 'labor_costs', ['date'], unique=False)
    op.create_index('idx_labor_costs_created_by', 'labor_costs', ['created_by_id'], unique=False)
    op.alter_column('labor_costs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('labor_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_costs', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('equipment_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_orders', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Причина отказа в заявке',
               existing_nullable=True)
    op.alter_column('equipment_costs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'delivery_costs', type_='foreignkey')
    op.create_foreign_key('delivery_costs_created_by_id_fkey', 'delivery_costs', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_delivery_costs_id'), table_name='delivery_costs')
    op.drop_index(op.f('ix_delivery_costs_date'), table_name='delivery_costs')
    op.drop_index(op.f('ix_delivery_costs_created_by_id'), table_name='delivery_costs')
    op.drop_index(op.f('ix_delivery_costs_cost_type'), table_name='delivery_costs')
    op.drop_index(op.f('ix_delivery_costs_cost_object_id'), table_name='delivery_costs')
    op.create_index('idx_delivery_costs_type', 'delivery_costs', ['cost_type'], unique=False)
    op.create_index('idx_delivery_costs_object', 'delivery_costs', ['cost_object_id'], unique=False)
    op.create_index('idx_delivery_costs_date', 'delivery_costs', ['date'], unique=False)
    op.create_index('idx_delivery_costs_created_by', 'delivery_costs', ['created_by_id'], unique=False)
    op.alter_column('delivery_costs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('delivery_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_costs', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key('deliveries_cost_object_id_fkey', 'deliveries', 'cost_objects', ['cost_object_id'], ['id'])
    op.create_foreign_key('deliveries_created_by_id_fkey', 'deliveries', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivery_date'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_by_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_cost_object_id'), table_name='deliveries')
    op.create_index('idx_deliveries_status', 'deliveries', ['status'], unique=False)
    op.create_index('idx_deliveries_object', 'deliveries', ['cost_object_id'], unique=False)
    op.create_index('idx_deliveries_date', 'deliveries', ['delivery_date'], unique=False)
    op.create_index('idx_deliveries_created_by', 'deliveries', ['created_by_id'], unique=False)
    op.alter_column('deliveries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('deliveries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.create_unique_constraint('cost_objects_code_key', 'cost_objects', ['code'])
    op.alter_column('cost_objects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_objects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('cost_objects', 'budget_alert_100_sent')
    op.drop_column('cost_objects', 'budget_alert_80_sent')
    op.drop_column('cost_objects', 'budget_amount')
    op.alter_column('cost_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_brigades_id'), table_name='brigades')
    op.alter_column('brigades', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brigades', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('brigade_members', sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('brigade_members', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_brigade_members_id'), table_name='brigade_members')
    op.alter_column('brigade_members', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brigade_members', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('brigade_members', 'phone')
    op.drop_index(op.f('ix_time_sheet_comments_time_sheet_id'), table_name='time_sheet_comments')
    op.drop_index(op.f('ix_time_sheet_comments_id'), table_name='time_sheet_comments')
    op.drop_table('time_sheet_comments')
    op.drop_index(op.f('ix_upd_distribution_history_material_cost_id'), table_name='upd_distribution_history')
    op.drop_index(op.f('ix_upd_distribution_history_id'), table_name='upd_distribution_history')
    op.drop_table('upd_distribution_history')
    op.drop_index(op.f('ix_telegram_link_codes_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_code'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    op.drop_index(op.f('ix_object_access_requests_status'), table_name='object_access_requests')
    op.drop_index(op.f('ix_object_access_requests_id'), table_name='object_access_requests')
    op.drop_table('object_access_requests')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
