"""Add fields to equipment_costs and material_request_items

Revision ID: fb5610ce5e43
Revises: 011
Create Date: 2026-01-26 12:23:56.027097

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5610ce5e43'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brigades_foreman_id_fkey', 'brigades', type_='foreignkey')
    op.create_foreign_key(None, 'brigades', 'users', ['foreman_id'], ['id'], ondelete='CASCADE')
    op.add_column('cost_entries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index('ix_cost_entries_object_date', table_name='cost_entries')
    op.create_index(op.f('ix_cost_entries_date'), 'cost_entries', ['date'], unique=False)
    op.create_index(op.f('ix_cost_entries_id'), 'cost_entries', ['id'], unique=False)
    op.drop_constraint('cost_entries_cost_object_id_fkey', 'cost_entries', type_='foreignkey')
    op.create_foreign_key(None, 'cost_entries', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_cost_objects_status', table_name='cost_objects')
    op.drop_index('ix_cost_objects_code', table_name='cost_objects')
    op.create_index(op.f('ix_cost_objects_code'), 'cost_objects', ['code'], unique=True)
    op.create_index(op.f('ix_cost_objects_id'), 'cost_objects', ['id'], unique=False)
    op.create_index(op.f('ix_cost_objects_status'), 'cost_objects', ['status'], unique=False)
    op.add_column('equipment_costs', sa.Column('work_date', sa.Date(), nullable=False))
    op.add_column('equipment_costs', sa.Column('delivery_included', sa.Boolean(), nullable=True))
    op.add_column('equipment_costs', sa.Column('delivery_amount', sa.Float(), nullable=True))
    op.add_column('equipment_costs', sa.Column('penalty_included', sa.Boolean(), nullable=True))
    op.add_column('equipment_costs', sa.Column('penalty_amount', sa.Float(), nullable=True))
    op.add_column('equipment_costs', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_equipment_costs_id'), 'equipment_costs', ['id'], unique=False)
    op.drop_column('equipment_costs', 'date')
    op.alter_column('equipment_orders', 'foreman_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment_orders', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('equipment_orders', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_equipment_orders_number', table_name='equipment_orders')
    op.create_index(op.f('ix_equipment_orders_id'), 'equipment_orders', ['id'], unique=False)
    op.create_unique_constraint(None, 'equipment_orders', ['number'])
    op.drop_constraint('equipment_orders_cost_object_id_fkey', 'equipment_orders', type_='foreignkey')
    op.drop_constraint('equipment_orders_foreman_id_fkey', 'equipment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'equipment_orders', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'equipment_orders', 'users', ['foreman_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_material_cost_items_id'), 'material_cost_items', ['id'], unique=False)
    op.drop_column('material_cost_items', 'created_at')
    op.drop_column('material_cost_items', 'updated_at')
    op.alter_column('material_costs', 'supplier_inn',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.create_index(op.f('ix_material_costs_document_date'), 'material_costs', ['document_date'], unique=False)
    op.create_index(op.f('ix_material_costs_id'), 'material_costs', ['id'], unique=False)
    op.create_index(op.f('ix_material_costs_status'), 'material_costs', ['status'], unique=False)
    op.drop_constraint('material_costs_cost_object_id_fkey', 'material_costs', type_='foreignkey')
    op.create_foreign_key(None, 'material_costs', 'cost_objects', ['cost_object_id'], ['id'], ondelete='SET NULL')
    op.drop_column('material_costs', 'vat_rate')
    op.add_column('material_request_items', sa.Column('distributed_quantity', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.create_index(op.f('ix_material_request_items_id'), 'material_request_items', ['id'], unique=False)
    op.drop_column('material_request_items', 'created_at')
    op.drop_column('material_request_items', 'notes')
    op.drop_column('material_request_items', 'updated_at')
    op.alter_column('material_requests', 'foreman_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_requests', 'urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'обычная'"))
    op.drop_index('idx_material_requests_type', table_name='material_requests')
    op.drop_index('ix_material_requests_number', table_name='material_requests')
    op.create_index(op.f('ix_material_requests_id'), 'material_requests', ['id'], unique=False)
    op.create_index(op.f('ix_material_requests_material_type'), 'material_requests', ['material_type'], unique=False)
    op.create_unique_constraint(None, 'material_requests', ['number'])
    op.drop_constraint('material_requests_foreman_id_fkey', 'material_requests', type_='foreignkey')
    op.drop_constraint('material_requests_cost_object_id_fkey', 'material_requests', type_='foreignkey')
    op.create_foreign_key(None, 'material_requests', 'users', ['foreman_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'material_requests', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.drop_column('material_requests', 'approved_at')
    op.create_index(op.f('ix_time_sheet_items_id'), 'time_sheet_items', ['id'], unique=False)
    op.drop_constraint('time_sheet_items_member_id_fkey', 'time_sheet_items', type_='foreignkey')
    op.drop_constraint('time_sheet_items_cost_object_id_fkey', 'time_sheet_items', type_='foreignkey')
    op.create_foreign_key(None, 'time_sheet_items', 'brigade_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'time_sheet_items', 'cost_objects', ['cost_object_id'], ['id'], ondelete='CASCADE')
    op.drop_column('time_sheet_items', 'created_at')
    op.drop_column('time_sheet_items', 'hourly_rate')
    op.drop_column('time_sheet_items', 'updated_at')
    op.drop_column('time_sheet_items', 'total_amount')
    op.add_column('time_sheets', sa.Column('hour_rate', sa.Float(), nullable=True))
    op.add_column('time_sheets', sa.Column('total_hours', sa.Float(), nullable=True))
    op.add_column('time_sheets', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('time_sheets', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_index('ix_time_sheets_number', table_name='time_sheets')
    op.create_index(op.f('ix_time_sheets_id'), 'time_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_time_sheets_period_start'), 'time_sheets', ['period_start'], unique=False)
    op.create_unique_constraint(None, 'time_sheets', ['number'])
    op.drop_constraint('time_sheets_brigade_id_fkey', 'time_sheets', type_='foreignkey')
    op.create_foreign_key(None, 'time_sheets', 'brigades', ['brigade_id'], ['id'], ondelete='CASCADE')
    op.drop_column('time_sheets', 'submitted_at')
    op.drop_column('time_sheets', 'approved_at')
    op.alter_column('upd_distribution', 'material_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_upd_distribution_id'), 'upd_distribution', ['id'], unique=False)
    op.drop_constraint('upd_distribution_material_cost_item_id_fkey', 'upd_distribution', type_='foreignkey')
    op.drop_constraint('upd_distribution_cost_object_id_fkey', 'upd_distribution', type_='foreignkey')
    op.drop_constraint('upd_distribution_material_request_id_fkey', 'upd_distribution', type_='foreignkey')
    op.create_foreign_key(None, 'upd_distribution', 'material_requests', ['material_request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('upd_distribution', 'material_cost_item_id')
    op.drop_column('upd_distribution', 'cost_object_id')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.add_column('upd_distribution', sa.Column('cost_object_id', sa.INTEGER(), nullable=True))
    op.add_column('upd_distribution', sa.Column('material_cost_item_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'upd_distribution', type_='foreignkey')
    op.create_foreign_key(None, 'upd_distribution', 'material_cost_items', ['material_cost_item_id'], ['id'])
    op.create_foreign_key(None, 'upd_distribution', 'cost_objects', ['cost_object_id'], ['id'])
    op.create_foreign_key(None, 'upd_distribution', 'material_requests', ['material_request_id'], ['id'])
    op.drop_index(op.f('ix_upd_distribution_id'), table_name='upd_distribution')
    op.alter_column('upd_distribution', 'material_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('time_sheets', sa.Column('approved_at', sa.DATETIME(), nullable=True))
    op.add_column('time_sheets', sa.Column('submitted_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'time_sheets', type_='foreignkey')
    op.create_foreign_key(None, 'time_sheets', 'brigades', ['brigade_id'], ['id'])
    op.drop_constraint(None, 'time_sheets', type_='unique')
    op.drop_index(op.f('ix_time_sheets_period_start'), table_name='time_sheets')
    op.drop_index(op.f('ix_time_sheets_id'), table_name='time_sheets')
    op.create_index('ix_time_sheets_number', 'time_sheets', ['number'], unique=False)
    op.drop_column('time_sheets', 'notes')
    op.drop_column('time_sheets', 'total_amount')
    op.drop_column('time_sheets', 'total_hours')
    op.drop_column('time_sheets', 'hour_rate')
    op.add_column('time_sheet_items', sa.Column('total_amount', sa.FLOAT(), nullable=True))
    op.add_column('time_sheet_items', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('time_sheet_items', sa.Column('hourly_rate', sa.FLOAT(), nullable=True))
    op.add_column('time_sheet_items', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_constraint(None, 'time_sheet_items', type_='foreignkey')
    op.drop_constraint(None, 'time_sheet_items', type_='foreignkey')
    op.create_foreign_key(None, 'time_sheet_items', 'brigade_members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'time_sheet_items', 'cost_objects', ['cost_object_id'], ['id'])
    op.drop_index(op.f('ix_time_sheet_items_id'), table_name='time_sheet_items')
    op.add_column('material_requests', sa.Column('approved_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'material_requests', type_='foreignkey')
    op.drop_constraint(None, 'material_requests', type_='foreignkey')
    op.create_foreign_key(None, 'material_requests', 'cost_objects', ['cost_object_id'], ['id'])
    op.create_foreign_key(None, 'material_requests', 'users', ['foreman_id'], ['id'])
    op.drop_constraint(None, 'material_requests', type_='unique')
    op.drop_index(op.f('ix_material_requests_material_type'), table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_id'), table_name='material_requests')
    op.create_index('ix_material_requests_number', 'material_requests', ['number'], unique=False)
    op.create_index('idx_material_requests_type', 'material_requests', ['material_type'], unique=False)
    op.alter_column('material_requests', 'urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'обычная'"))
    op.alter_column('material_requests', 'foreman_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('material_request_items', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('material_request_items', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('material_request_items', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_material_request_items_id'), table_name='material_request_items')
    op.alter_column('material_request_items', 'distributed_quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.add_column('material_costs', sa.Column('vat_rate', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'material_costs', type_='foreignkey')
    op.create_foreign_key(None, 'material_costs', 'cost_objects', ['cost_object_id'], ['id'])
    op.drop_index(op.f('ix_material_costs_status'), table_name='material_costs')
    op.drop_index(op.f('ix_material_costs_id'), table_name='material_costs')
    op.drop_index(op.f('ix_material_costs_document_date'), table_name='material_costs')
    op.alter_column('material_costs', 'supplier_inn',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('material_cost_items', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('material_cost_items', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_material_cost_items_id'), table_name='material_cost_items')
    op.drop_constraint(None, 'equipment_orders', type_='foreignkey')
    op.drop_constraint(None, 'equipment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'equipment_orders', 'cost_objects', ['cost_object_id'], ['id'])
    op.create_foreign_key(None, 'equipment_orders', 'users', ['foreman_id'], ['id'])
    op.drop_constraint(None, 'equipment_orders', type_='unique')
    op.drop_index(op.f('ix_equipment_orders_id'), table_name='equipment_orders')
    op.create_index('ix_equipment_orders_number', 'equipment_orders', ['number'], unique=False)
    op.alter_column('equipment_orders', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('equipment_orders', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('equipment_orders', 'foreman_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('equipment_costs', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_index(op.f('ix_equipment_costs_id'), table_name='equipment_costs')
    op.drop_column('equipment_costs', 'description')
    op.drop_column('equipment_costs', 'penalty_amount')
    op.drop_column('equipment_costs', 'penalty_included')
    op.drop_column('equipment_costs', 'delivery_amount')
    op.drop_column('equipment_costs', 'delivery_included')
    op.drop_column('equipment_costs', 'work_date')
    op.drop_index(op.f('ix_cost_objects_status'), table_name='cost_objects')
    op.drop_index(op.f('ix_cost_objects_id'), table_name='cost_objects')
    op.drop_index(op.f('ix_cost_objects_code'), table_name='cost_objects')
    op.create_index('ix_cost_objects_code', 'cost_objects', ['code'], unique=False)
    op.create_index('idx_cost_objects_status', 'cost_objects', ['status'], unique=False)
    op.drop_constraint(None, 'cost_entries', type_='foreignkey')
    op.create_foreign_key(None, 'cost_entries', 'cost_objects', ['cost_object_id'], ['id'])
    op.drop_index(op.f('ix_cost_entries_id'), table_name='cost_entries')
    op.drop_index(op.f('ix_cost_entries_date'), table_name='cost_entries')
    op.create_index('ix_cost_entries_object_date', 'cost_entries', ['cost_object_id', 'date'], unique=False)
    op.drop_column('cost_entries', 'updated_at')
    op.drop_constraint(None, 'brigades', type_='foreignkey')
    op.create_foreign_key(None, 'brigades', 'users', ['foreman_id'], ['id'])
    # ### end Alembic commands ###
